### ISSUE TITLE
Filenav does not seem to work on the current Pythonista

### ISSUE THREAD

**Issue by cclauss** [dgelessus/pythonista-scripts#16]

**Comment by dgelessus** [comment]
You might need to move the `filenav` package folder into `site-packages` for imports to work.

**Comment by cclauss** [comment]
What is `the filenav package folder`?  I move filenav.py into site-packages but that changed nothing.

**Comment by cclauss** [comment]
Oh...  Now I see that there is a separate [filenav repo](https://github.com/dgelessus/filenav) that probably works better than this standalone filenav.py which does not work.

**Comment by dgelessus** [comment]
Oh, you were still using the old one. That explains a lot. I guess I should put some kind of big notice at the top of the old filenav to point people to the new version.
